apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-deploy
spec:
  selector:
    matchLabels:
      app: webapp1
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: amikacr.azurecr.io/python-test:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp1-svc
spec:
  selector:
    app: webapp1
  ports:
  - port: 80
  type: ClusterIP # LoadBalancer # NodePort # 
